library(readr)
EDC_renset_data <- read_csv2("~/Desktop/OLA1/EDC_renset_data.csv")
View(EDC_renset_data)
Ny=EDC_renset_data[-c(6), -c(11, 15, 19, 20, 21, 22, 23, 24)]
Ny1=na.omit(Ny)
model.linreg1 <- lm( Ny1$Pris_m_ ~ Ny1$pris, data = Ny1 )
summary(model.linreg)
model.linreg2 <- lm( Ny1$Pris_m_ ~ Ny1$zip, data = Ny1 )
summary(model.linreg2)
model.linreg3 <- lm( Ny1$Pris_m_ ~ Ny1$Liggetid, data = Ny1 )
summary(model.linreg3)
model.linreg4 <- lm( Ny1$Pris_m_ ~ Ny1$Boligareal, data = Ny1 )
summary(model.linreg4)
model.linreg5 <- lm( Ny1$Pris_m_ ~ Ny1$Ejerudgifter_pr__md_, data = Ny1 )
summary(model.linreg5)
Matr=Ny1[, -c(1, 2, 4, 6, 7, 8, 9, 10, 14, 15, 16)]
Korrelationsmatrix=cor(Matr)
model.linreg6 <- lm( Ny1$Ejerudgifter_pr__md_ ~ Ny1$Pris_m_, data = Ny1 )
summary(model.linreg6)
plot(Matr$Pris_m_, Matr$Boligareal)
plot(Matr$Pris_m_, Matr$pris)
plot(Matr$Pris_m_, Matr$zip)
plot(Matr$Pris_m_, Matr$Liggetid)
plot(Matr$Pris_m_, Matr$Boligareal)
plot(Matr$Pris_m_, Matr$Ejerudgifter_pr__md_)
